const ITEMS = [{"seq": 1, "location": "Chicken Cooler", "name": "Chicken", "packSize": "8 Bags", "pack": 8},
    {"seq": 2, "location": "Chicken Cooler", "name": "Chicken Wings", "packSize": "1 Case", "pack": 1},
    {"seq": 3, "location": "Chicken Cooler", "name": "Breast", "packSize": "80 Per Case", "pack": 80},
    {"seq": 4, "location": "Chicken Cooler", "name": "Legs", "packSize": "125 Per Case", "pack": 125},
    {"seq": 5, "location": "Stockroom - Chicken", "name": "Tallow Shortening Vat Fryer - Liquid", "packSize": "1 Box", "pack": 1},
    {"seq": 6, "location": "Stockroom - Chicken", "name": "Tallow Shortening Vat Fryer - Cube", "packSize": "1 Box", "pack": 1},
    {"seq": 7, "location": "Stockroom - Chicken", "name": "Breading Flour", "packSize": "1 Bag", "pack": 1},
    {"seq": 8, "location": "Stockroom - Chicken", "name": "Chicken Batter Dip", "packSize": "10 Packs", "pack": 10},
    {"seq": 9, "location": "Stockroom - Chicken", "name": "Royal Mild", "packSize": "40 Packs", "pack": 40},
    {"seq": 10, "location": "Freezer", "name": "Chicken Supremes", "packSize": "8 Bags", "pack": 8},
    {"seq": 12, "location": "Cooler", "name": "Premade Dries", "packSize": "6 Bags", "pack": 6},
    {"seq": 13, "location": "Cooler", "name": "Coleslaw Dressing Mixture", "packSize": "20 Bags", "pack": 20},
    {"seq": 14, "location": "Cooler", "name": "Cheddar Cheese", "packSize": "6 Packs = 192 Slices", "pack": 6},
    {"seq": 15, "location": "Freezer", "name": "French Fries", "packSize": "6 Bags", "pack": 6},
    {"seq": 16, "location": "Freezer", "name": "Bo Rounds", "packSize": "6 Bags", "pack": 6},
    {"seq": 17, "location": "Freezer", "name": "Cinnamon Twist", "packSize": "6 Boxes / 18 Each", "pack": 6},
    {"seq": 18, "location": "Freezer", "name": "Sweet Potato Pie", "packSize": "72 Each - 1 Box", "pack": 72},
    {"seq": 19, "location": "Freezer", "name": "Blueberry Pellet", "packSize": "1 Box", "pack": 1},
    {"seq": 20, "location": "Stockroom - Sides", "name": "Pinto Beans", "packSize": "6 Cans", "pack": 6},
    {"seq": 21, "location": "Freezer", "name": "Mac and Cheese", "packSize": "8 Bags", "pack": 8},
    {"seq": 22, "location": "Stockroom - Sides", "name": "Mashed Potatoes", "packSize": "36 Packs", "pack": 36},
    {"seq": 23, "location": "Stockroom - Sides", "name": "Rice Long Grain", "packSize": "1 Bag", "pack": 1},
    {"seq": 24, "location": "Stockroom - Biscuits", "name": "Icing - Vanilla", "packSize": "24 Packs", "pack": 24},
    {"seq": 25, "location": "Stockroom - Biscuits", "name": "Cinnamon Sugar", "packSize": "6 Bags", "pack": 6},
    {"seq": 26, "location": "Stockroom - Sides", "name": "Cajun Gravy White", "packSize": "20 Packs", "pack": 20},
    {"seq": 27, "location": "Stockroom - Sides", "name": "French Fry Seasoning", "packSize": "25 Packs", "pack": 25},
    {"seq": 28, "location": "Stockroom - Sides", "name": "Pintos Seasoning", "packSize": "120 Packs", "pack": 120},
    {"seq": 29, "location": "Stockroom - Sides", "name": "Dirty Rice Seasoning", "packSize": "100 Packs", "pack": 100},
    {"seq": 30, "location": "Cooler", "name": "American Cheese", "packSize": "8 Sleeves", "pack": 8},
    {"seq": 31, "location": "Breakfast Meats", "name": "Steak", "packSize": "6 Boxes / 46 Per Box", "pack": 6},
    {"seq": 32, "location": "Breakfast Meats", "name": "Smoked Sausage", "packSize": "70 Per Case", "pack": 70},
    {"seq": 34, "location": "Breakfast Meats", "name": "Country Ham", "packSize": "3 Packs", "pack": 3},
    {"seq": 35, "location": "Breakfast Meats", "name": "Bacon", "packSize": "4 Packs", "pack": 4},
    {"seq": 36, "location": "Breakfast Meats", "name": "Sausage ", "packSize": "2 Boxes", "pack": 2},
    {"seq": 37, "location": "Cooler", "name": "Eggs", "packSize": "15 Containers", "pack": 15},
    {"seq": 38, "location": "Cooler", "name": "Whipped Margarine (Tub)", "packSize": "1 Tub", "pack": 1},
    {"seq": 39, "location": "Cooler", "name": "Liquid Margarine", "packSize": "2 Containers", "pack": 2},
    {"seq": 41, "location": "Stockroom - Biscuits", "name": "Self Rising Biscuit Flour", "packSize": "8 Bags", "pack": 8},
    {"seq": 42, "location": "Stockroom - Biscuits", "name": "Biscuit Magic", "packSize": "96 Each", "pack": 96},
    {"seq": 43, "location": "Cooler", "name": "Buttermilk", "packSize": "9 Per Case", "pack": 9},
    {"seq": 44, "location": "Cooler", "name": "1% White Milk", "packSize": "24 Per Case", "pack": 24},
    {"seq": 45, "location": "Cooler", "name": "Chocolate Milk", "packSize": "24 Per Case", "pack": 24},
    {"seq": 47, "location": "Cooler", "name": "Lemons", "packSize": "1 Box = 8 Lb = 32 Each", "pack": 32},
    {"seq": 48, "location": "Cooler", "name": "Orange Juice", "packSize": "24 Per Case", "pack": 24},
    {"seq": 49, "location": "Cooler", "name": "Half and Half Creamer", "packSize": "360 Each", "pack": 360},
    {"seq": 50, "location": "Drinks", "name": "Diet Pepsi", "packSize": "1 Box", "pack": 1},
    {"seq": 51, "location": "Drinks", "name": "Diet Mountain Dew", "packSize": "1 Box", "pack": 1},
    {"seq": 52, "location": "Stockroom - Sides", "name": "Ranch Seasoning", "packSize": "96 Packs", "pack": 96},
    {"seq": 53, "location": "Cooler", "name": "French Vanilla Creamer", "packSize": "1 Box = 288 Each", "pack": 288},
    {"seq": 54, "location": "Sauce/Condiments", "name": "Sweetener Yellow Packets", "packSize": "3000 Packs", "pack": 3000},
    {"seq": 55, "location": "Drinks", "name": "Mountain Dew", "packSize": "1 Box", "pack": 1},
    {"seq": 56, "location": "Drinks", "name": "Pepsi", "packSize": "1 Box", "pack": 1},
    {"seq": 57, "location": "Sauce/Condiments", "name": "Sugar Packet", "packSize": "3000 Packs", "pack": 3000},
    {"seq": 58, "location": "Sauce/Condiments", "name": "Sweetener Pink", "packSize": "3000 Packs", "pack": 3000},
    {"seq": 59, "location": "Drinks", "name": "Decaf Coffee", "packSize": "64 Each", "pack": 64},
    {"seq": 60, "location": "Drinks", "name": "Tea Bags", "packSize": "110 Each", "pack": 110},
    {"seq": 61, "location": "Drinks", "name": "Hot Tea Bags - Individuals", "packSize": "1 - Box = 100 Each", "pack": 1},
    {"seq": 62, "location": "Drinks", "name": "Regular Coffee (Silver)", "packSize": "176 Packs", "pack": 176},
    {"seq": 67, "location": "Stockroom - Sides", "name": "Grits", "packSize": "8 Bags", "pack": 8},
    {"seq": 69, "location": "Drinks", "name": "Lemonade", "packSize": "1 Box", "pack": 1},
    {"seq": 70, "location": "Drinks", "name": "Dr. Pepper", "packSize": "1 Box", "pack": 1},
    {"seq": 71, "location": "Drinks", "name": "Water Bottle", "packSize": "24 Bottles Per Case", "pack": 24},
    {"seq": 72, "location": "OLD", "name": "OLD - Ranch Sauce", "packSize": "216 Each", "pack": 216},
    {"seq": 73, "location": "Stockroom", "name": "Sugar (4 lb. bags)", "packSize": "10 Bags / 4 lb each", "pack": 10},
    {"seq": 74, "location": "Sauce/Condiments", "name": "Margarine  Cups", "packSize": "600/ Each", "pack": 600},
    {"seq": 77, "location": "Sauce/Condiments", "name": "Bo Special Sauce Cups", "packSize": "216 Each", "pack": 216},
    {"seq": 78, "location": "Sauce/Condiments", "name": "Salt Packet", "packSize": "6 Bags", "pack": 6},
    {"seq": 79, "location": "Sauce/Condiments", "name": "Pepper Packet", "packSize": "6 Bags", "pack": 6},
    {"seq": 80, "location": "Sauce/Condiments", "name": "Ketchup Packets", "packSize": "1500 Each", "pack": 1500},
    {"seq": 81, "location": "Sauce/Condiments", "name": "Mustard Packets", "packSize": "500 Each", "pack": 500},
    {"seq": 82, "location": "Sauce/Condiments", "name": "Mayo Packets", "packSize": "500 Each", "pack": 500},
    {"seq": 83, "location": "Sauce/Condiments", "name": "Hot Sauce Packets", "packSize": "500 Each", "pack": 500},
    {"seq": 84, "location": "Sauce/Condiments", "name": "BBQ Sauce Cups", "packSize": "216 Each", "pack": 216},
    {"seq": 85, "location": "Sauce/Condiments", "name": "Honey Mustard Sauce Cups", "packSize": "216 Each", "pack": 216},
    {"seq": 86, "location": "Sauce/Condiments", "name": "Grape Jelly Packet", "packSize": "500 Each", "pack": 500},
    {"seq": 87, "location": "Sauce/Condiments", "name": "Honey Packet", "packSize": "200 Each", "pack": 200},
    {"seq": 90, "location": "Chicken Cooler", "name": "Bo Bites", "packSize": "8 Bags", "pack": 8},
    {"seq": 93, "location": "OLD", "name": "OLD - Lettuce McLane", "packSize": "2 /1 Lb", "pack": 2},
    {"seq": 94, "location": "Cooler", "name": "Tomato", "packSize": "25 Lbs", "pack": 25},
    {"seq": 95, "location": "Breakfast Meats", "name": "Cajun Filets", "packSize": "6 Bags / 5 Lb", "pack": 6},
    {"seq": 96, "location": "Breakfast Meats", "name": "Grilled Filets", "packSize": "8 Bags - 144 Each", "pack": 8},
    {"seq": 97, "location": "Breakfast Meats", "name": "Bologna", "packSize": "30 Packs", "pack": 30},
    {"seq": 98, "location": "Sauce/Condiments", "name": "Peach Honey Pepper Sauce Cups", "packSize": "216 Each", "pack": 216},
    {"seq": 99, "location": "Stockroom - Paper", "name": "Black Ranch Cups 2.75 Oz", "packSize": "2500 Cups", "pack": 2500},
    {"seq": 100, "location": "Stockroom - Paper", "name": "Lid Flat 20 oz (Ice Coffee Lids)", "packSize": "10 Sleeves / Cs", "pack": 10},
    {"seq": 101, "location": "Stockroom - Paper", "name": "Cup Plastic Clear 20 oz (Ice Coffee Cups)", "packSize": "20 Sleeves / Cs", "pack": 20},
    {"seq": 103, "location": "Stockroom - Paper", "name": "16 oz Hot Coffee Cups", "packSize": "20 Sleeves", "pack": 20},
    {"seq": 104, "location": "Stockroom - Paper", "name": "16-22 oz Cold Cup Lids", "packSize": "24 Sleeves", "pack": 24},
    {"seq": 105, "location": "Stockroom - Paper", "name": "32 oz Cold Cup Lids", "packSize": "10 Sleeves", "pack": 10},
    {"seq": 106, "location": "Stockroom - Paper", "name": "16 oz Hot Coffee Lids - Black", "packSize": "12 Sleeves", "pack": 12},
    {"seq": 107, "location": "Stockroom - Paper", "name": "16 oz Cold Drink Cups", "packSize": "24 Sleeves", "pack": 24},
    {"seq": 108, "location": "Stockroom - Paper", "name": "22 oz Cold Drink Cups", "packSize": "24 Sleeves", "pack": 24},
    {"seq": 109, "location": "Stockroom - Paper", "name": "32 oz Cold Drinks Cups", "packSize": "25 Sleeves", "pack": 25},
    {"seq": 112, "location": "Stockroom - Paper", "name": "4 oz Cole Slaw Cup - Black", "packSize": "25 Sleeves", "pack": 25},
    {"seq": 113, "location": "Stockroom - Paper", "name": "4 oz Hot Food Container (Individual)", "packSize": "35 Sleeves", "pack": 35},
    {"seq": 114, "location": "Stockroom - Paper", "name": "16 oz Hot Food Containers (Picnic)", "packSize": "20 Sleeves = 500 Each", "pack": 20},
    {"seq": 116, "location": "Stockroom - Paper", "name": "1/2 Gallon Jugs", "packSize": "108 Each", "pack": 108},
    {"seq": 117, "location": "Stockroom - Paper", "name": "Red Caps for 1/2 Gallon Jugs", "packSize": "2400 Each", "pack": 2400},
    {"seq": 118, "location": "Stockroom - Paper", "name": "16 oz Picnic Lids", "packSize": "10 Sleeves", "pack": 10},
    {"seq": 119, "location": "Stockroom - Paper", "name": "3 Compartment Plates", "packSize": "4 Packs", "pack": 4},
    {"seq": 120, "location": "Stockroom - Paper", "name": "Oval Platter", "packSize": "4 Packs", "pack": 4},
    {"seq": 121, "location": "Stockroom - Paper", "name": "Drink Carrier", "packSize": "4 Sleeves", "pack": 4},
    {"seq": 122, "location": "Stockroom - Paper", "name": "Food Tray / Boat", "packSize": "4 Packs", "pack": 4},
    {"seq": 123, "location": "Stockroom - Paper", "name": "Chicken Boxes", "packSize": "250 Each", "pack": 250},
    {"seq": 124, "location": "Stockroom - Paper", "name": "Dinner Boxes", "packSize": "400 Each", "pack": 400},
    {"seq": 125, "location": "Stockroom - Paper", "name": "Napkins", "packSize": "12 Packs", "pack": 12},
    {"seq": 126, "location": "Stockroom - Paper", "name": "4 oz Cole Slaw Lid", "packSize": "25 Sleeves", "pack": 25},
    {"seq": 127, "location": "Stockroom - Paper", "name": "4 oz Hot Food Lids - White", "packSize": "20 Sleeves", "pack": 20},
    {"seq": 128, "location": "Stockroom - Paper", "name": "Black Salad Bowls", "packSize": "6 Sleeves", "pack": 6},
    {"seq": 129, "location": "Stockroom - Paper", "name": "Dome Lids for Salad Bowl", "packSize": "3 Sleeves", "pack": 3},
    {"seq": 130, "location": "Stockroom - Paper", "name": "Knife Black Wrapped", "packSize": "1000 Each", "pack": 1000},
    {"seq": 131, "location": "Stockroom - Paper", "name": "Sporks Black", "packSize": "1000 Each", "pack": 1000},
    {"seq": 132, "location": "Stockroom - Paper", "name": "Fork & Knife Kit", "packSize": "500 Each", "pack": 500},
    {"seq": 135, "location": "Stockroom - Paper", "name": "Wrap - Deli Paper 12 X 10.5", "packSize": "12 Boxes", "pack": 12},
    {"seq": 136, "location": "Stockroom - Paper", "name": "Wrap - Bisc (Yellow)", "packSize": "4 Packs = 4000", "pack": 4},
    {"seq": 137, "location": "Stockroom - Paper", "name": "Wrap - Bisc Ham 100", "packSize": "4 Packs = 4000", "pack": 4},
    {"seq": 138, "location": "Stockroom - Paper", "name": "Wrap - Bisc Sausage", "packSize": "4 Packs = 4000", "pack": 4},
    {"seq": 139, "location": "Stockroom - Paper", "name": "Wrap - Bisc Steak", "packSize": "4 Packs = 4000", "pack": 4},
    {"seq": 140, "location": "Stockroom - Paper", "name": "Wrap - Bisc Bacon", "packSize": "4 Packs = 4000", "pack": 4},
    {"seq": 141, "location": "Stockroom - Paper", "name": "Wrap - Bisc Chicken & Un-Printed Wrap - (6 Packs)", "packSize": "4 Packs = 4000", "pack": 4},
    {"seq": 142, "location": "Stockroom - Paper", "name": "Carton Pie 500", "packSize": "500 Each", "pack": 500},
    {"seq": 143, "location": "Stockroom - Paper", "name": "French Fry Carton - Picnic", "packSize": "1000 Each", "pack": 1000},
    {"seq": 144, "location": "Stockroom - Paper", "name": "French Fry Bags - Individual", "packSize": "2500 Each", "pack": 2500},
    {"seq": 145, "location": "Stockroom - Paper", "name": "Small Bags - 4 lb.", "packSize": "6 Packs", "pack": 6},
    {"seq": 146, "location": "Stockroom - Paper", "name": "Medium Bags - 6 lb.", "packSize": "4 Packs", "pack": 4},
    {"seq": 147, "location": "Stockroom - Paper", "name": "Large Bag - 12 lb.", "packSize": "2 Packs / 500", "pack": 2},
    {"seq": 148, "location": "Stockroom - Paper", "name": "Bag White Jumbo Sacks - 50 lb.", "packSize": "500 Each", "pack": 500},
    {"seq": 149, "location": "Stockroom - Paper", "name": "Tray Liners", "packSize": "1000 Each", "pack": 1000},
    {"seq": 150, "location": "Stockroom - Paper", "name": "Wrap - Foil Red", "packSize": "4 Packs = 2000", "pack": 4},
    {"seq": 155, "location": "Stockroom - Paper", "name": "Pan Liners", "packSize": "2000 Each", "pack": 2000},
    {"seq": 156, "location": "Stockroom - Paper", "name": "Drinking Straws", "packSize": "24 Boxes/500 Each", "pack": 24},
    {"seq": 157, "location": "Stockroom - Paper", "name": "Coffee Stirrer", "packSize": "500 Each", "pack": 500},
    {"seq": 161, "location": "Cleaning", "name": "Can Liner (33 x 40)", "packSize": "10 Rolls", "pack": 10},
    {"seq": 162, "location": "Cleaning", "name": "Can Liner (43 x 48)", "packSize": "8 Rolls", "pack": 8},
    {"seq": 170, "location": "Cleaning", "name": "Green Scouring Pads", "packSize": "6 Pack", "pack": 6},
    {"seq": 171, "location": "Cleaning", "name": "Stainless Steel Scrubbers", "packSize": "12 Each", "pack": 12},
    {"seq": 173, "location": "Sauce/Condiments", "name": "Strawberry Jam Packet", "packSize": "500 Each", "pack": 500},
    {"seq": 177, "location": "Cleaning", "name": "Chlorine Test", "packSize": "Each", "pack": null},
    {"seq": 178, "location": "Cooler", "name": "Diced Cabbage", "packSize": "4 - 3.125 Lbs", "pack": 4},
    {"seq": 179, "location": "Cleaning", "name": "Sizzle Cleaner", "packSize": "4 Bottles", "pack": 4},
    {"seq": 180, "location": "Freezer", "name": "Fish", "packSize": "40 Pieces", "pack": 40},
    {"seq": 181, "location": "Cooler", "name": "Tartar Sauce", "packSize": "1 Gallon", "pack": 1},
    {"seq": 182, "location": "Chicken Cooler", "name": "Thigh / Leg Split", "packSize": "10 Bags", "pack": 10},
    {"seq": 183, "location": "Cleaning", "name": "Sink Sanitizer Packets", "packSize": "200 Each", "pack": 200},
    {"seq": 184, "location": "Stockroom - Paper", "name": "Coffee Box", "packSize": "30 Each", "pack": 30},
    {"seq": 201, "location": "Cooler", "name": "Shredded Cheese", "packSize": "4 Bags", "pack": 4},
    {"seq": 202, "location": "Sauce/Condiments", "name": "Salad Dressing - Thousand Island", "packSize": "60 Packets", "pack": 60},
    {"seq": 203, "location": "Sauce/Condiments", "name": "Salad Dressing - Balsamic Vinaigrette", "packSize": "60 Packets", "pack": 60},
    {"seq": 204, "location": "Sauce/Condiments", "name": "Salad Dressing - Blue Cheese", "packSize": "60 Packets", "pack": 60},
    {"seq": 205, "location": "Sauce/Condiments", "name": "Salad Dressing - Honey Dijon", "packSize": "60 Packets", "pack": 60},
    {"seq": 206, "location": "Sauce/Condiments", "name": "Salad Dressing - Ranch (0)", "packSize": "60 Packets", "pack": 60},
    {"seq": 207, "location": "Sauce/Condiments", "name": "Captain Wafers Crackers", "packSize": "500 Each", "pack": 500},
    {"seq": 208, "location": "Sauce/Condiments", "name": "Croutons", "packSize": "200 Each", "pack": 200},
    {"seq": 209, "location": "Sauce/Condiments", "name": "Salad Dressing - Fat Free Ranch", "packSize": "60 Packets", "pack": 60},
    {"seq": 213, "location": "Breakfast Meats", "name": "Pork Chop", "packSize": "4 Boxes", "pack": 4},
    {"seq": 214, "location": "Cooler", "name": "Cucumbers", "packSize": "1 Box = 3 Each", "pack": 3},
    {"seq": 215, "location": "Cooler", "name": "Grape Tomatos", "packSize": "2 - 2 Lb Boxes", "pack": 2},
    {"seq": 216, "location": "Cooler", "name": "Salad Blend / Salad Mix", "packSize": "4/ 2 Lb Bags", "pack": 4},
    {"seq": 218, "location": "Stockroom - Paper", "name": "Big Bo Box", "packSize": "60 Each", "pack": 60},
    {"seq": 219, "location": "Cooler", "name": "Shredded Lettuce", "packSize": "4/2.5 Lb", "pack": 4},
    {"seq": 220, "location": "Stockroom - Paper", "name": "Aluminum Foil Pop-up Sheets", "packSize": "1 Box", "pack": 1},
    {"seq": 224, "location": "Cooler", "name": "Pimento Cheese", "packSize": "4 - 5Lb Tubs", "pack": 4},
    {"seq": 229, "location": "Cleaning", "name": "Kay QSR Multi Surface Cleaner", "packSize": "2 Bags", "pack": 2},
    {"seq": 230, "location": "Cleaning", "name": "Kay Sink Detergent", "packSize": "2 Bags", "pack": 2},
    {"seq": 231, "location": "Cleaning", "name": "Kay Heavy Duty Degreaser", "packSize": "2 Bags", "pack": 2},
    {"seq": 232, "location": "Cleaning", "name": "Kay Quarry Floor Tile Cleaner 2/2 Gallon Bag", "packSize": "2 Bags", "pack": 2},
    {"seq": 234, "location": "Stockroom", "name": "Indiv Sale Fry Seasoning (24/2)", "packSize": "24 / 2 Packs", "pack": 24},
    {"seq": 283, "location": "Cleaning", "name": "Hand Soap", "packSize": "4/1 Gl", "pack": 4},
    {"seq": 284, "location": "Cleaning", "name": "Wiper Green White 20X13", "packSize": "200 Ct", "pack": 200},
    {"seq": 285, "location": "Cleaning", "name": "Hybrid Glove - Small", "packSize": "10 Boxes", "pack": 10},
    {"seq": 286, "location": "Cleaning", "name": "Hybrid Glove - Medium", "packSize": "10 Boxes", "pack": 10},
    {"seq": 287, "location": "Cleaning", "name": "Hybrid Glove - Large", "packSize": "10 Boxes", "pack": 10},
    {"seq": 288, "location": "Cleaning", "name": "Hybrid Glove - Extra Large", "packSize": "5 Bx/ 200 Ea", "pack": 5},
    {"seq": 290, "location": "Cleaning", "name": "Plastic Bag", "packSize": "500 Each", "pack": 500},
    {"seq": 291, "location": "Stockroom - Paper", "name": "Wrap - Special Wrap", "packSize": "1 Box", "pack": 1},
    {"seq": 299, "location": "Stockroom - Paper", "name": "Face Mask", "packSize": "1 Box", "pack": 1},
    {"seq": 304, "location": "Stockroom - Paper", "name": "Wrap - Biscuit Plain", "packSize": "8 Packs = 8000", "pack": 8},
    {"seq": 305, "location": "Drinks", "name": "Starry", "packSize": "1 Box = 5 Gallons", "pack": 1},
    {"seq": 306, "location": "Drinks", "name": "Pepsi Zero", "packSize": "1 - Box = 5 Gallons", "pack": 1},
    {"seq": 308, "location": "Drinks", "name": "Cheerwine", "packSize": "1 Box = 5 Gallons", "pack": 1},
    {"seq": 309, "location": "Drinks", "name": "Cold Brew", "packSize": "6 Bottles / Cs", "pack": 6},
    {"seq": 310, "location": "Drinks", "name": "Sweet Cream Vanilla", "packSize": "6 Cartons / Cs", "pack": 6},
    {"seq": 311, "location": "Drinks", "name": "Vanilla Syrup", "packSize": "12 Bottles / Cs", "pack": 12},
    {"seq": 312, "location": "Drinks", "name": "Caramel Sauce", "packSize": "4 Bottles / Cs", "pack": 4},
    {"seq": 314, "location": "Freezer", "name": "Buns - Bird Dog", "packSize": "14Pk/12Ea = 168 Case", "pack": 14},
    {"seq": 315, "location": "Stockroom", "name": "Carolina BBQ Sauce - Bird Dog", "packSize": "4/1 Gl", "pack": 4},
    {"seq": 321, "location": "Stockroom - Paper", "name": "Sandwich Clamshell", "packSize": "4 Sleeves = 500", "pack": 4},
    {"seq": 326, "location": "Sauce/Condiments", "name": "Creamy Buffalo Sauce Cups", "packSize": "1 Box = 216 Each    2 Ounce Cups", "pack": 1},
    {"seq": 329, "location": "Stockroom - Chicken", "name": "Dura Fry", "packSize": "1 Box", "pack": 1},
    {"seq": 330, "location": "Freezer", "name": "Bun Split Top 4", "packSize": "15 Packs = 1 Case", "pack": 15},
    {"seq": 331, "location": "Stockroom - Chicken", "name": "Bo Batter", "packSize": "10 Packs", "pack": 10},
    {"seq": 332, "location": "Stockroom - Chicken", "name": "Bo Breading", "packSize": "1 Bag", "pack": 1},
    {"seq": 333, "location": "Cooler", "name": "Savory Mayo", "packSize": "8 Packs", "pack": 8},
    {"seq": 334, "location": "Chicken Cooler", "name": "Bo Chicken", "packSize": "8 Bags", "pack": 8},
    {"seq": 335, "location": "Cooler", "name": "Pickles", "packSize": "1 Bucket = 1000", "pack": 1},
    {"seq": 360, "location": "Virginia", "name": "Clamshell Fiber (VA Locations Only)", "packSize": null, "pack": null},
    {"seq": 361, "location": "Virginia", "name": "Container Picnic Lw 16 Oz (VA Locations Only)", "packSize": null, "pack": null},
    {"seq": 362, "location": "Virginia", "name": "Lid Picnic 12 - 16 Ounce (VA Locations Only)", "packSize": null, "pack": null},
    {"seq": 363, "location": "Virginia", "name": "Lid 32 Oz Cup (VA Locations Only)", "packSize": null, "pack": null},
    {"seq": 364, "location": "Virginia", "name": "Cup Paper 32 Oz (VA Locations Only)", "packSize": null, "pack": null},
    {"seq": 365, "location": "Catering", "name": "Box Corrugated (Catering)", "packSize": "30 Each", "pack": 30},
    {"seq": 366, "location": "Catering", "name": "Cont Fix 80 Oz (Catering)", "packSize": "50 Each", "pack": 50},
    {"seq": 367, "location": "Catering", "name": "Lid Fix 80 Oz (Catering)", "packSize": "50 Each", "pack": 50},
    {"seq": 368, "location": "Catering", "name": "Pan Foil 100 (Catering)", "packSize": "100 Each", "pack": 100},
    {"seq": 369, "location": "Catering", "name": "Lid Foil 100 (Catering)", "packSize": "100 Each", "pack": 100},
    {"seq": 370, "location": "Catering", "name": "Bag Nonwoven (Catering)", "packSize": "25", "pack": 25},
    {"seq": 371, "location": "Catering", "name": "Tong Serv 48 (Catering)", "packSize": "48 Each", "pack": 48},
    {"seq": 372, "location": "Catering", "name": "Spoon Serve (Catering)", "packSize": "144 Each", "pack": 144},
    ];
